### PR TITLE
Return io.WriteCloser instead of io.Writer

### PR DESCRIPTION
**Pull request by techtonik**
Because os.Stdout is *os.File which supports Close method

### CODE REVIEW

**Comment by techtonik** [comment]
This is used in LXD project which calls Close when it was fed with file in place of os.Stdout

**Comment by mattn** [comment]
Why you don't Close like `os.Stdout.Close()` in your self?

https://github.com/mattn/go-colorable/blob/master/colorable_others.go#L10-L16

**Comment by mattn** [comment]
Please show me the code that have problem.

**Comment by techtonik** [comment]
This is my original commit (it was rebased in PR below) https://github.com/techtonik/lxd/commit/71e56e4be5920e09369cdecbdada38cd19f041f8

This is the discussion that followed it https://github.com/lxc/lxd/pull/1291#issuecomment-155364615

**Comment by mattn** [comment]
well, you are not using my package. right?

https://github.com/techtonik/lxd/commit/71e56e4be5920e09369cdecbdada38cd19f041f8#diff-16293fbd98ec07b8bafdc6dfd3cbef23R10

**Comment by techtonik** [comment]
@mattn I do - https://github.com/techtonik/lxd/commit/4a2ab1f1b78c3ed962adea181d36671a800e83a5 but it is not submitted as PR yet, because I can not test that it works as expected right now. So I wanted to check if we can remove the crutches that were inserted to deal with absence of `io.WriteCloser` in `shiena/ansicolor` interface - https://github.com/lxc/lxd/commit/2f39a8bde2ff71eb3427f53d23e1a5d9b8e4e6c4#diff-16293fbd98ec07b8bafdc6dfd3cbef23

**Comment by mattn** [comment]
If possible please remain the implement of wrapper with colorable. because I'm worrying about changes of interface.
How do you think?

**Comment by techtonik** [comment]
I am a newbie in Go, so I can't think much. For me changing the interface won't break anything, because it is an extension - functions that accept `io.Writer` will accept `io.WriteCloser`, right?

I don't understand why somebody will need to close os.Stdout and what will happen if you actually close it. I can understand why people need io.WriteCloser which is swappable with os.Stdout - to redirect output to file, but again - I still don't see who should close the file. For me the one who provides stream should close it - not some function down the stack. Maybe we just need a proper PR in LXC to show this pattern.

**Comment by mattn** [comment]
>I am a newbie in Go, so I can't think much. For me changing the interface won't break anything, because it is an extension - functions that accept io.Writer will accept io.WriteCloser, right?

Yes, right. But this change interface. So if someone expect go-colorable should be io.Writer, it break compatible. For example, see below.

```go
package main

import (
	"github.com/mattn/go-colorable"
	"io"
	"os"
)

var a io.Writer

func handleWriter(w io.Writer) {
	switch w.(type) {
	case io.WriteCloser:
		println("maybe, it's not go-colorable")
	case io.Writer:
		println("maybe, it's go-colorable")
	}
}

func main() {
	handleWriter(colorable.NewColorableStdout())
	handleWriter(os.Stdout)
}
```
Note that run on terminal.

This works before this change. but in after, doesn't work. While this change may not be a big deal, I don't like change of interface.

**Comment by techtonik** [comment]
I think that wrapper should return the interface it is wrapping. So if os.Stdout is File, the colorable.NewColorableStdout() should also return File.

**Comment by mattn** [comment]
Yes, I mean you have better to provide the wrapper until I will confirm this change don't have any problem at least.

**Comment by techtonik** [comment]
Pending. https://github.com/lxc/lxd/pull/1331

**Comment by mattn** [comment]
Okay, thanks. I'll have to work later.

**Comment by dolmen** [comment]
Another good reason to use a `io.WriterCloser` is that access to `Close` would allow to implement buffering in particular to handle ANSI sequences which are split in 2 (or more) `Write` calls.

**Comment by mattn** [comment]
The reason that I don't still merge this PR, The Writer on Windows doesn't a `*os.File`.

**Comment by techtonik** [comment]
This becomes too complicated for me, so feel free to fork or close this.

**Comment by mattn** [comment]
Okay, I'll close this. If you still have problems. Please file new issue. Thanks.

**Pull request closed without merging**
