### PR TITLE
Add third person singular `s` in comments

### PR DESCRIPTION
**Pull request by toshimaru**
I think this is a typo, so fixed it.

```
// Write write data on console
```

### CODE REVIEW

**Comment by zetamatta** [comment]
The first `Write` looks to be the method name(noun) rather than verb for me.

**Comment by mattn** [comment]
I prefer "Write writes" like below.

https://golang.org/pkg/io/#WriteString

**Comment by toshimaru** [comment]
> I prefer "Write writes" like below.

Okay 👍 , I've added `s` for third person singulars and changed PR title.

**Comment by mattn** [comment]
Thank you

**Pull request merged**
