### PR TITLE
vendorized godep workspace

### PR DESCRIPTION
**Pull request by moret**
Hi. I'm using go-colorable indirectly via a chain of dependencies. Following the instructions of godep - https://github.com/tools/godep/issues/131 - I declared and added the godep workspace vendorized to the project with `godep save`.

### CODE REVIEW

**Comment by mattn** [comment]
Sorry I don't understand why you need this PR.

**Comment by moret** [comment]
My fault, I should have asked if you'd like that first 8) . I'm using Gin, and just recently I ran a `godep restore` in a clean installation and noticed that some of the project's dependencies do not have the Godeps folder and vendorized depedencies. So I saved them, and thought you might want it. But I totally understand if you prefer no to have them.

Sorry for the unprompted PR.

**Comment by mattn** [comment]
Thanks for your suggestion. But I don't think it has some merits.

**Comment by moret** [comment]
:+1:

**Pull request closed without merging**
